import { env } from 'cloudflare:workers';
import { decode } from 'fast-png';

export const PROJECT_ID = 'search-party';
export const imageModels = new Map([
  ['fal-ai/flux-pro/kontext', { label: 'FLUX.1 Kontext Pro', cost: '0.04' }],
  ['fal-ai/nano-banana/edit', { label: 'Nano Banana Edit', cost: '0.039' }],
  ['fal-ai/bytedance/seedream/v4.5/edit', { label: 'Seedream 4.5 Edit', cost: '0.04' }],
  ['fal-ai/flux-pro/kontext/max', { label: 'FLUX.1 Kontext Max', cost: '0.08' }],
]);
export const json = (body: unknown, status = 200) => Response.json(body, { status, headers: { 'cache-control': 'no-store' } });
export function localOnly(request: Request) { const host = new URL(request.url).hostname; return host === 'localhost' || host === '127.0.0.1'; }
export function getBindings() { let key: string|undefined, db: D1Database|undefined, files: R2Bucket|undefined; try { key=env.FAL_KEY; db=env.DB; files=env.FILES; } catch {} return {key,db,files}; }
export async function ensureImageSchema(db:D1Database){await db.batch([
 db.prepare("CREATE TABLE IF NOT EXISTS quotes (id text PRIMARY KEY NOT NULL,project_id text NOT NULL,provider text NOT NULL,model text NOT NULL,payload_hash text NOT NULL,payload_json text NOT NULL,max_cost_usd text NOT NULL,currency text NOT NULL DEFAULT 'USD',expires_at integer NOT NULL,created_at integer NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS paid_approvals (id text PRIMARY KEY NOT NULL,project_id text NOT NULL,quote_id text NOT NULL,quote_payload_hash text NOT NULL,approval_snapshot_json text NOT NULL,actor_id text NOT NULL,idempotency_key text NOT NULL,approved_at integer NOT NULL,created_at integer NOT NULL)"),
 db.prepare("CREATE UNIQUE INDEX IF NOT EXISTS paid_approvals_idempotency_unique ON paid_approvals(project_id,idempotency_key)"),
 db.prepare("CREATE TABLE IF NOT EXISTS generation_runs (id text PRIMARY KEY NOT NULL,project_id text NOT NULL,shot_id text,approval_id text,provider text NOT NULL,model text NOT NULL,request_hash text NOT NULL,request_snapshot_json text NOT NULL,reference_snapshot_json text NOT NULL DEFAULT '[]',status text NOT NULL DEFAULT 'queued',provider_request_id text,provider_response_json text,started_at integer,completed_at integer,created_at integer NOT NULL,updated_at integer)"),
 db.prepare("CREATE UNIQUE INDEX IF NOT EXISTS generation_runs_request_unique ON generation_runs(project_id,request_hash)"),
 db.prepare("CREATE TABLE IF NOT EXISTS jobs (id text PRIMARY KEY NOT NULL,quote_id text NOT NULL,run_id text,status text NOT NULL,provider_request_id text,actual_cost_usd text,result_asset_id text,retry_count integer NOT NULL DEFAULT 0,last_error_code text,last_error_safe_message text,created_at integer NOT NULL,updated_at integer)"),
 db.prepare("CREATE TABLE IF NOT EXISTS assets (id text PRIMARY KEY NOT NULL,project_id text NOT NULL,canonical_asset_id text,shot_id text,type text NOT NULL,version text NOT NULL,status text NOT NULL,storage_key text,media_url text,mime_type text,byte_size integer,width integer,height integer,duration_ms integer,sha256 text,prompt_snapshot_json text,lineage_json text NOT NULL,created_at integer NOT NULL,updated_at integer)"),
 db.prepare("CREATE TABLE IF NOT EXISTS reviews (id text PRIMARY KEY NOT NULL,project_id text NOT NULL,asset_id text NOT NULL,run_id text,reviewer_id text NOT NULL,reviewer_kind text NOT NULL,verdict text NOT NULL,checklist_json text NOT NULL DEFAULT '{}',note text,supersedes_review_id text,created_at integer NOT NULL)"),
 db.prepare("CREATE TABLE IF NOT EXISTS shot_selections (id text PRIMARY KEY NOT NULL,project_id text NOT NULL,shot_id text NOT NULL,canonical_asset_id text NOT NULL,asset_revision_id text,role text NOT NULL,locked integer NOT NULL DEFAULT 0,notes text,created_at integer NOT NULL,updated_at integer)"),
 db.prepare("CREATE UNIQUE INDEX IF NOT EXISTS shot_selections_unique_role ON shot_selections(shot_id,canonical_asset_id,role)"),
]);}
export async function sha256(value: string|ArrayBuffer) { const bytes=typeof value==='string'?new TextEncoder().encode(value):value; const digest=await crypto.subtle.digest('SHA-256',bytes); return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join(''); }
export function parsePng(buffer:ArrayBuffer){try{const decoded=decode(new Uint8Array(buffer),{checkCrc:true});if(!decoded.width||!decoded.height||!decoded.data.length)throw new Error('empty pixels');const colorMode=decoded.palette?'indexed':decoded.channels===4?'RGBA':decoded.channels===3?'RGB':decoded.channels===2?'grayscale-alpha':'grayscale';return{width:decoded.width,height:decoded.height,colorMode}}catch{throw new Error('Fal returned a PNG that failed full pixel decoding or CRC validation.')}}

export type StoredRun={runId:string;jobId:string;shotId:string;model:string;modelLabel:string;estimatedCost:string;prompt:string;sourceImageUrl:string;requestId?:string;status:'submitting'|'queued'|'running'|'completed'|'failed';createdAt:string;updatedAt:string;logs:string[];outputUrl?:string;assetId?:string;assetStatus?:string;version?:string;sha256?:string;width?:number;height?:number;colorMode?:string;error?:string};
type RunRow={run_id:string;job_id:string;shot_id:string;model:string;status:string;provider_request_id:string|null;request_snapshot_json:string;provider_response_json:string|null;created_at:number;updated_at:number|null;result_asset_id:string|null;last_error_safe_message:string|null;media_url:string|null;asset_status:string|null;version:string|null;sha256:string|null;width:number|null;height:number|null;mime_type:string|null};
export function rowToRun(row:RunRow):StoredRun{const snapshot=JSON.parse(row.request_snapshot_json) as {prompt?:string;imageUrl?:string;modelLabel?:string;estimatedCost?:string};const response=row.provider_response_json?JSON.parse(row.provider_response_json) as {logs?:string[];colorMode?:string}:{};const status=(['submitting','queued','running','completed','failed'].includes(row.status)?row.status:'queued') as StoredRun['status'];return{runId:row.run_id,jobId:row.job_id,shotId:row.shot_id,model:row.model,modelLabel:snapshot.modelLabel??imageModels.get(row.model)?.label??row.model,estimatedCost:snapshot.estimatedCost??`$${imageModels.get(row.model)?.cost??'?'} / image`,prompt:snapshot.prompt??'',sourceImageUrl:snapshot.imageUrl??'',requestId:row.provider_request_id??undefined,status,createdAt:new Date(row.created_at*1000).toISOString(),updatedAt:new Date((row.updated_at??row.created_at)*1000).toISOString(),logs:response.logs??[],outputUrl:row.media_url??undefined,assetId:row.result_asset_id??undefined,assetStatus:row.asset_status??undefined,version:row.version??undefined,sha256:row.sha256??undefined,width:row.width??undefined,height:row.height??undefined,colorMode:response.colorMode,error:row.last_error_safe_message??undefined};}
export const runSelect=`SELECT gr.id AS run_id,j.id AS job_id,gr.shot_id,gr.model,gr.status,gr.provider_request_id,gr.request_snapshot_json,gr.provider_response_json,gr.created_at,gr.updated_at,j.result_asset_id,j.last_error_safe_message,a.media_url,a.status AS asset_status,a.version,a.sha256,a.width,a.height,a.mime_type FROM generation_runs gr JOIN jobs j ON j.run_id=gr.id LEFT JOIN assets a ON a.id=j.result_asset_id`;
